server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

jasypt:
  encryptor:
    password: password # 암호화에 사용할 Passowrd 설정
    bean: jasyptStringEncryptor # Bean 이름

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/template/
      suffix: .jsp
    converters:
      preferred-json-mapper: gson
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
