jasypt:
  encryptor:
    password: "${password}" # 암호화에 사용할 Passowrd 설정

spring:
  datasource:
    url: ENC(tmt4LJIxSWxcWrHjgLb6qOSBA+opDb7aM6Pfp29TeGE2q6W02gC+B/AKjMmpRSZdrHRYX0IiiDq6Qgu3jWceGa0rOhnSoW44)
    #driver-class-name: ENC(AKaNZGwQG6u2E7LYXcwK3aZZ6toeD7cLUb0CAcK+tUJFkJwaPp0Usg==)
    username: ENC(ltNBgjsUTTEvaF7NbpeSzA==)
    password: ENC(wtWsOAlclIGOo0VeudJMXP3QKfmPlDrGTtf6yLa/ehw=)
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      maximum-pool-size: 3

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  config: classpath:log4j2-dev.xml
