jasypt:
  encryptor:
    password: "${password}" # 암호화에 사용할 Passowrd 설정
    #bean: jasyptStringEncryptor # Bean 이름

spring:
  datasource:
    url: ENC(AU/dk5T4m6DVlLhY4K2gff/2PzN6OCcnIFttUohlG1yFehbeE6NEzr9ZRelPDsq29l8pzXcRQyJU1ovglC0WGeMxQmqGXkR8)
    driver-class-name: ENC(fdbiVGhMKIHnOr3iboiZfuQYp7YKiX7ZXXBG42SzpaDAIRrJY1DNXg==)
    username: ENC(zR1a2jzGz/EwAfIUcz6v4Q==)
    password: ENC(OxXErUtM9pUhD+bO5Pi2PFNDEz+KuveX)

logging:
  config: classpath:log4j2-dev.xml
