server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR

spring:
  aop:
    proxy-target-class: true
  mvc:
    view:
      prefix: /WEB-INF/template/
      suffix: .jsp
    converters:
      preferred-json-mapper: gson

---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tnsqja012@gmail.com
    password: gdbfiuukveuucjte
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true