jasypt:
  encryptor:
    password: "${password}" # 암호화에 사용할 Passowrd 설정
    bean: jasyptStringEncryptor # Bean 이름

spring:
  datasource:
    url: ENC(obiFG6cJsmR1erpg46K0QmUuKW0LY4Bm2fhZKtM6/bi7JfXTuR8MWGc7yswxf8QyIMGdL6iyYjuehsBUG1MfGziw989Ttv1ZFI35ZM/4RH9DJDSZgGNsQOj3NJprUIXQ)
    driver-class-name: ENC(Buur8cwc8t/JoN/14LwTVivPQDSdf4ZmFF8tgUqyZwLMwH91HFqxCcj8J/Dq6pvc)
    username: ENC(UHt96JlmrJnnGxC0kDYQXA==)
    password: ENC(qBXfL3kT/WKsvL6S7wpzkVuDBQegEbdl)

logging:
  config: classpath:log4j2-local.xml
