name: App install and start

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deployment:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        clean: false

    - name: Use Java Version
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Source Git Pull
      run: |
        cd ../../
        ./git-pull.sh
        
    - name: Stop old server
      run: |
        cd ../../
        ./down-server.sh
        
    - name: Run new server (in background)
      env:
        RUNNER_TRACKING_ID: ""
      run: |
        cd ../../
        ./start-server.sh
